def get_lctofisent_query():
    return """
    SELECT 
        A.DATAEMISSAO,
        A.CHAVENFEENT,
        A.NUMERONF,
        A.ESPECIENF,
        A.SERIENF,
        PESSOA_B.NomePessoa as NOMEPESSOA,
        B.CODIGOCFOP,
        B.VALORCONTABILIMPOSTO,
        B.BASECALCULOIMPOSTO,
        B.VALORIMPOSTO,
        A.VALORIPI
    FROM LCTOFISENT A
    LEFT JOIN LCTOFISENTCFOP B
        ON A.CODIGOEMPRESA = B.CODIGOEMPRESA
        AND A.CHAVELCTOFISENT = B.CHAVELCTOFISENT
    LEFT JOIN Pessoa PESSOA_B
        ON PESSOA_B.CODIGOPESSOA = A.CODIGOPESSOA
    LEFT JOIN CFOP X
        ON X.CODIGOEMPRESA = B.CODIGOEMPRESA
        AND X.CODIGOESTAB = B.CODIGOESTAB
        AND X.CODIGOCFOP = B.CODIGOCFOP
    WHERE A.CODIGOEMPRESA = (
          SELECT e.CODIGOEMPRESA
          FROM ESTAB e
          WHERE e.INSCRFEDERAL = %s
      )
    AND A.CODIGOESTAB = (
          SELECT e.CODIGOESTAB
          FROM ESTAB e
          WHERE e.INSCRFEDERAL = %s
      )
    AND A.CDMODELO IN ('55', '57', '65')
    AND A.DATALCTOFIS BETWEEN %s AND %s
    """