def get_lctofissai_query():
    return """
    SELECT 
        A.DATALCTOFIS,
        A.CHAVENFESAI,
        A.NUMERONF,
        A.ESPECIENF,
        A.SERIENF,
        PESSOA_B.NomePessoa,
        B.CODIGOCFOP,
        B.VALORCONTABILIMPOSTO,
        B.BASECALCULOIMPOSTO,
        B.VALORIMPOSTO,
        A.VALORIPI
    FROM LCTOFISSAI A
    LEFT JOIN LCTOFISSAICFOP B
        ON A.CODIGOEMPRESA = B.CODIGOEMPRESA
        AND A.CHAVELCTOFISSAI = B.CHAVELCTOFISSAI
    LEFT JOIN Pessoa PESSOA_B
        ON PESSOA_B.CODIGOPESSOA = A.CODIGOPESSOA
    LEFT JOIN CFOP X
        ON X.CODIGOEMPRESA = B.CODIGOEMPRESA
        AND X.CODIGOESTAB = B.CODIGOESTAB
        AND X.CODIGOCFOP = B.CODIGOCFOP
    WHERE A.CODIGOEMPRESA = (
        SELECT e.CODIGOEMPRESA
        FROM ESTAB e
        WHERE e.INSCRFEDERAL = %s
    )
    AND A.CODIGOESTAB = (
        SELECT e.CODIGOESTAB
        FROM ESTAB e
        WHERE e.INSCRFEDERAL = %s
    )
    AND A.CODIGOTIPODCTOSINTEGRA IN (55, 57, 65)
    AND A.DATALCTOFIS BETWEEN %s AND %s
    """